### ISSUE TITLE
Installation issue and code implementation

### ISSUE THREAD

**Issue by johnreytanquinco** [KristianI/cvrapi#1]
Hi Kristiani,

I am interested in how your code works as I'm doing the same implementation in my current project.
In my case, I use Drupal 8 site, writing a views plugin to query data from the CVR api. As a newbie in PHP environment, while I was studying your code, I see that your cvrapi/src/Cvrapi/Cvrapi.php could be use as my client file to pull data from the api.

I'm getting stuck in this project since what I want to accomplish is just simple but can't achieve it.
First step I made is just download your file as zip and copy all related files(Validate, Config) inside my plugin folder.

I cannot install your package using composer as I'm getting this error.
 `[InvalidArgumentException]
  Could not find package kristiani/cvrapi at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`

Am I missing something in installing your package?

Also, I tried doing Unit Test also with your provided code, but doesn't work in me.

Correct me if I'm wrong, I did a little configuration in your file, setting up hard-coded values under request function.

//set as vat
$search = 123456789;
$country = 'dk';

Still doesn't receiving any output from the api.

Your help is highly appreciated!
Thanks!
![screen shot 2017-02-08 at 5 57 21 pm](https://cloud.githubusercontent.com/assets/7284893/22733429/b362532a-ee2c-11e6-958e-338ef66ab362.png)

**Comment by KristianI** [comment]
Hi 

I have released a stable version of the package in packagist.
Please try running `composer require kristiani/cvrapi` again, and it should meet your minimum-stability setting.

Regarding the Unit Tests, please share the errors you are receiving, and I will be able to help you further.

Best regards
Kristian

**Comment by johnreytanquinco** [comment]
Hi Kristian,

Thanks for your quick response.
I tried adding dev-master and it works. Also rerun your default installation code and its fine now.
![screen shot 2017-02-08 at 8 02 24 pm](https://cloud.githubusercontent.com/assets/7284893/22736578/bc2dd968-ee39-11e6-828d-d02b6a9aae64.png)

What I'm trying to achieve is that once user will input the VAT value and data will be pulled from the api, using the views query plugin I'm writing and display the output in the view.

I have a CVR.php file below that pulled data from the client(which is your Cvr.php).
http://pastebin.com/TBMwiVdW

On the execute function, in line 54, I expect that $data['vat'] will pull the vat values from the client. It will be then assign to row['vat'] which I set as field in the views UI. Since I want to test it if it is functioning as what is expected, I added hard-coded values in the client file. I assume that the $search variable can be inputted with the vat value.

I would really appreciate if you can review my code and give me corrections on it.

Thank you so mcuh!
John Rey

**Comment by KristianI** [comment]
Hi John

I don't know how your CVRClient is implemented, but you should be able to call `$response = \Cvrapi\Cvrapi::get('my search value', 'dk', 'my project name');` from anywhere in your project if the composer package is autoloaded. 'my search value' could be either VAT number, P-number or company name.

Try running `var_dump($response);` after the get-call to get an idea of how the output is formatted.

In https://github.com/KristianI/cvrapi/blob/master/README.md I have given a few examples of the usage.

Best regards
Kristian

**Comment by johnreytanquinco** [comment]
Hi Kristian,

Thank you so much. That solved my issue. I have one more concern. How can I limit the search to only accept vat values? As I believe in your code, it has multiple allowed types of search. Thanks in advance!

Regards,
John Rey

**Comment by johnreytanquinco** [comment]
Hi Kristian,

Thank you so much. That solved my issue. I have one more concern. How can I limit the search to only accept vat values? As I believe in your code, it has multiple allowed types of search. Thanks in advance!

Regards,
John Rey

**Comment by KristianI** [comment]
Hi John Rey

You can use the request method with the vat option. It will search in vat values only.

Example:
$result = \Cvrapi\Cvrapi::request('29910251', 'dk', 'vat', 'Description of my project');
